// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Ch0Ix-yzJBFTAlVwhStRvcIMXOpfHbc',
    appId: '1:35271381062:web:1dac82d20617926a0a3a47',
    messagingSenderId: '35271381062',
    projectId: 'moodpad-flutter-project',
    authDomain: 'moodpad-flutter-project.firebaseapp.com',
    storageBucket: 'moodpad-flutter-project.firebasestorage.app',
    measurementId: 'G-08Y9N95SSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCtQevVxR6Czslb1oO7Ac6GIXJW3N0I3k',
    appId: '1:35271381062:android:bc0c67064946ac960a3a47',
    messagingSenderId: '35271381062',
    projectId: 'moodpad-flutter-project',
    storageBucket: 'moodpad-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK2ltimS0sFaLM95WKnYposlhUKwcVQd0',
    appId: '1:35271381062:ios:c775b69d0aa2c51a0a3a47',
    messagingSenderId: '35271381062',
    projectId: 'moodpad-flutter-project',
    storageBucket: 'moodpad-flutter-project.firebasestorage.app',
    iosBundleId: 'com.makingstuffup.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK2ltimS0sFaLM95WKnYposlhUKwcVQd0',
    appId: '1:35271381062:ios:c775b69d0aa2c51a0a3a47',
    messagingSenderId: '35271381062',
    projectId: 'moodpad-flutter-project',
    storageBucket: 'moodpad-flutter-project.firebasestorage.app',
    iosBundleId: 'com.makingstuffup.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Ch0Ix-yzJBFTAlVwhStRvcIMXOpfHbc',
    appId: '1:35271381062:web:128ddcd66f03c80d0a3a47',
    messagingSenderId: '35271381062',
    projectId: 'moodpad-flutter-project',
    authDomain: 'moodpad-flutter-project.firebaseapp.com',
    storageBucket: 'moodpad-flutter-project.firebasestorage.app',
    measurementId: 'G-YPV4DPWF34',
  );
}
